Shell redirections task 8 fix

diff --git a/0x02-shell_redirections/8-cwd_state b/0x02-shell_redirections/8-cwd_state
--- a/0x02-shell_redirections/8-cwd_state
+++ b/0x02-shell_redirections/8-cwd_state
@@ -1,2 +1,7 @@
 #!bin/bash
-ls -la > ls_cwd_content
+ls -la >> ls_cwd_content
+if [ $? -eq 0 ]; then
+  echo "ls -la command executed successfully. Output saved to ls_cwd_content."
+else
+  echo "Error executing ls -la command."
+fi
